Added commands for successfull license removal for linux batchmode
alttester/EXAMPLES-Python-AWS-AltTrashCat pull request #3
Opened 2023-09-27 12:16 UTC by iulianatodoran

2023-09-27 14:35 UTC, gomboskriszta15 approved these changes

2023-10-10 05:44 UTC, RobertPoienar requested changes

2023-10-10 05:44 UTC, RobertPoienar commented on test-config.yml
> +      # for the local connection: export the license key, donwload, unzip and start the AltTester Desktop batchmode for Linux
```suggestion
      # for the local connection: export the license key, download, unzip and start the AltTester Desktop batchmode for Linux
```

2023-10-10 05:48 UTC, rucindrea approved these changes

2023-10-10 05:48 UTC, merged